token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
spring:
  application:
    name: spring-boot-metrics
management:
  metrics:
    tags:
      application: spring-boot-metrics
  endpoints:
    web:
      exposure:
        include: prometheus